// Terjemahan KONTEN produk (tagline, deskripsi, fitur) per id produk.
// Bahasa Indonesia diambil dari data asli (data/products.js) sebagai fallback,
// jadi di sini hanya 8 bahasa lain. Nama produk & brand tidak diterjemahkan.

export const PRODUCT_I18N = {
  'claude-pro': {
    tagline: { en: 'The smartest AI assistant for research, coding, and writing.', zh: '用于研究、编程和写作的最智能 AI 助手。', ja: 'リサーチ・コーディング・執筆に最適な最も賢いAIアシスタント。', ru: 'Умнейший AI-ассистент для исследований, кода и текстов.', ms: 'Pembantu AI paling pintar untuk penyelidikan, pengekodan & penulisan.', hi: 'रिसर्च, कोडिंग और लेखन के लिए सबसे स्मार्ट AI सहायक।', de: 'Der smarteste KI-Assistent für Recherche, Coding und Schreiben.', vi: 'Trợ lý AI thông minh nhất cho nghiên cứu, lập trình và viết.' },
    description: { en: 'Access all Claude models including Sonnet 4.6 and Opus 4.7, far beyond the free tier. Includes Claude Code, Cowork, Skills, and MCP for developer workflows, plus Research mode, unlimited Projects, extended thinking, and Microsoft 365 integration.', zh: '畅享包括 Sonnet 4.6 和 Opus 4.7 在内的所有 Claude 模型，远超免费版。包含面向开发者的 Claude Code、Cowork、Skills 和 MCP，以及研究模式、无限 Projects、扩展思考和 Microsoft 365 集成。', ja: 'Sonnet 4.6 や Opus 4.7 を含む全 Claude モデルに無料枠を超えてアクセス。開発者向けの Claude Code、Cowork、Skills、MCP に加え、リサーチモード、無制限 Projects、拡張思考、Microsoft 365 連携を搭載。', ru: 'Доступ ко всем моделям Claude, включая Sonnet 4.6 и Opus 4.7, далеко за пределами бесплатного тарифа. Включает Claude Code, Cowork, Skills и MCP для разработчиков, режим Research, безлимитные Projects, расширенное мышление и интеграцию с Microsoft 365.', ms: 'Akses semua model Claude termasuk Sonnet 4.6 dan Opus 4.7, jauh melebihi tier percuma. Termasuk Claude Code, Cowork, Skills & MCP untuk pembangun, mod Research, Projects tanpa had, pemikiran lanjutan & integrasi Microsoft 365.', hi: 'Sonnet 4.6 और Opus 4.7 सहित सभी Claude मॉडल तक पहुंच, फ्री टियर से कहीं अधिक। डेवलपर वर्कफ़्लो के लिए Claude Code, Cowork, Skills और MCP, साथ ही Research मोड, असीमित Projects, विस्तारित सोच और Microsoft 365 एकीकरण।', de: 'Zugang zu allen Claude-Modellen inkl. Sonnet 4.6 und Opus 4.7, weit über die Gratis-Stufe hinaus. Mit Claude Code, Cowork, Skills und MCP für Entwickler, Research-Modus, unbegrenzten Projects, erweitertem Denken und Microsoft-365-Integration.', vi: 'Truy cập mọi mô hình Claude gồm Sonnet 4.6 và Opus 4.7, vượt xa bản miễn phí. Bao gồm Claude Code, Cowork, Skills và MCP cho lập trình viên, chế độ Research, Projects không giới hạn, tư duy mở rộng và tích hợp Microsoft 365.' },
    features: {
      en: ['All Claude models (Sonnet 4.6 & Opus 4.7)', 'Claude Code, Cowork, Skills & MCP', 'Research, unlimited Projects, extended thinking', 'Microsoft 365 integration & voice mode'],
      zh: ['所有 Claude 模型（Sonnet 4.6 和 Opus 4.7）', 'Claude Code、Cowork、Skills 和 MCP', '研究模式、无限 Projects、扩展思考', 'Microsoft 365 集成与语音模式'],
      ja: ['全 Claude モデル（Sonnet 4.6 と Opus 4.7）', 'Claude Code、Cowork、Skills、MCP', 'リサーチ、無制限 Projects、拡張思考', 'Microsoft 365 連携と音声モード'],
      ru: ['Все модели Claude (Sonnet 4.6 и Opus 4.7)', 'Claude Code, Cowork, Skills и MCP', 'Research, безлимитные Projects, расширенное мышление', 'Интеграция с Microsoft 365 и голосовой режим'],
      ms: ['Semua model Claude (Sonnet 4.6 & Opus 4.7)', 'Claude Code, Cowork, Skills & MCP', 'Research, Projects tanpa had, pemikiran lanjutan', 'Integrasi Microsoft 365 & mod suara'],
      hi: ['सभी Claude मॉडल (Sonnet 4.6 और Opus 4.7)', 'Claude Code, Cowork, Skills और MCP', 'Research, असीमित Projects, विस्तारित सोच', 'Microsoft 365 एकीकरण और वॉइस मोड'],
      de: ['Alle Claude-Modelle (Sonnet 4.6 & Opus 4.7)', 'Claude Code, Cowork, Skills & MCP', 'Research, unbegrenzte Projects, erweitertes Denken', 'Microsoft-365-Integration & Sprachmodus'],
      vi: ['Mọi mô hình Claude (Sonnet 4.6 & Opus 4.7)', 'Claude Code, Cowork, Skills & MCP', 'Research, Projects không giới hạn, tư duy mở rộng', 'Tích hợp Microsoft 365 & chế độ giọng nói'],
    },
  },
  'claude-max-5x': {
    tagline: { en: '5x the capacity of Claude Pro for intensive users.', zh: '为重度用户提供 5 倍于 Claude Pro 的容量。', ja: 'ヘビーユーザー向けに Claude Pro の5倍の容量。', ru: 'В 5 раз больше ёмкости Claude Pro для интенсивной работы.', ms: 'Kapasiti 5x ganda Claude Pro untuk pengguna intensif.', hi: 'गहन उपयोगकर्ताओं के लिए Claude Pro की 5 गुना क्षमता।', de: 'Die 5-fache Kapazität von Claude Pro für Intensivnutzer.', vi: 'Dung lượng gấp 5 lần Claude Pro cho người dùng chuyên sâu.' },
    description: { en: '5x more usage capacity than Claude Pro with priority access during high traffic. Ideal for heavy daily users who often hit Pro limits, with full access to Opus 4.7 and all tooling including Claude Code.', zh: '使用容量是 Claude Pro 的 5 倍，高流量时享有优先访问。适合经常触及 Pro 限额的重度日常用户，可完整访问 Opus 4.7 及包括 Claude Code 在内的所有工具。', ja: 'Claude Pro の5倍の利用容量で、混雑時も優先アクセス。Pro の上限によく達するヘビーユーザーに最適で、Opus 4.7 と Claude Code を含む全ツールにフルアクセス。', ru: 'В 5 раз больше использования, чем у Claude Pro, с приоритетным доступом при высокой нагрузке. Идеально для активных пользователей; полный доступ к Opus 4.7 и всем инструментам, включая Claude Code.', ms: 'Kapasiti penggunaan 5x ganda Claude Pro dengan akses keutamaan ketika trafik tinggi. Sesuai untuk pengguna harian intensif, dengan akses penuh Opus 4.7 dan semua perkakas termasuk Claude Code.', hi: 'Claude Pro से 5 गुना अधिक उपयोग क्षमता, उच्च ट्रैफ़िक में प्राथमिकता पहुंच के साथ। भारी दैनिक उपयोगकर्ताओं के लिए आदर्श, Opus 4.7 और Claude Code सहित सभी टूल तक पूर्ण पहुंच।', de: '5-fache Nutzungskapazität gegenüber Claude Pro mit Prioritätszugang bei hoher Auslastung. Ideal für intensive Nutzer, mit vollem Zugang zu Opus 4.7 und allen Tools inkl. Claude Code.', vi: 'Dung lượng sử dụng gấp 5 lần Claude Pro với quyền ưu tiên khi lưu lượng cao. Lý tưởng cho người dùng cường độ cao, toàn quyền truy cập Opus 4.7 và mọi công cụ gồm Claude Code.' },
    features: {
      en: ['5x more usage than Claude Pro', 'Priority access during high traffic', 'Great for heavy daily users', 'Full Opus 4.7 + all tooling'],
      zh: ['使用量是 Claude Pro 的 5 倍', '高流量时优先访问', '适合重度日常用户', '完整 Opus 4.7 + 所有工具'],
      ja: ['Claude Pro の5倍の利用量', '混雑時も優先アクセス', 'ヘビーユーザーに最適', 'Opus 4.7 と全ツールにフルアクセス'],
      ru: ['В 5 раз больше использования, чем Claude Pro', 'Приоритетный доступ при нагрузке', 'Отлично для активных пользователей', 'Полный Opus 4.7 + все инструменты'],
      ms: ['Penggunaan 5x ganda Claude Pro', 'Akses keutamaan ketika trafik tinggi', 'Sesuai untuk pengguna harian intensif', 'Opus 4.7 penuh + semua perkakas'],
      hi: ['Claude Pro से 5 गुना अधिक उपयोग', 'उच्च ट्रैफ़िक में प्राथमिकता पहुंच', 'भारी दैनिक उपयोगकर्ताओं के लिए बढ़िया', 'पूर्ण Opus 4.7 + सभी टूल'],
      de: ['5x mehr Nutzung als Claude Pro', 'Prioritätszugang bei hoher Last', 'Ideal für intensive Nutzer', 'Voller Opus 4.7 + alle Tools'],
      vi: ['Sử dụng gấp 5 lần Claude Pro', 'Ưu tiên truy cập khi tải cao', 'Tuyệt cho người dùng cường độ cao', 'Opus 4.7 đầy đủ + mọi công cụ'],
    },
  },
  'claude-max-20x': {
    tagline: { en: 'Power-user class — 20x the capacity of Claude Pro.', zh: '高级用户级别 — 20 倍于 Claude Pro 的容量。', ja: 'パワーユーザー級 — Claude Pro の20倍の容量。', ru: 'Класс профи — в 20 раз больше ёмкости Claude Pro.', ms: 'Kelas pengguna kuasa — kapasiti 20x ganda Claude Pro.', hi: 'पावर-यूज़र क्लास — Claude Pro की 20 गुना क्षमता।', de: 'Power-User-Klasse — die 20-fache Kapazität von Claude Pro.', vi: 'Hạng người dùng nâng cao — gấp 20 lần Claude Pro.' },
    description: { en: '20x more usage capacity than Claude Pro — power-user class. Ideal for running several Claude Code instances in parallel, with top priority and full access to all models and features. Considered the best deal for a single power user.', zh: '使用容量是 Claude Pro 的 20 倍 — 高级用户级别。适合并行运行多个 Claude Code 实例，享有最高优先级和对所有模型与功能的完整访问。被认为是单一高级用户的最佳选择。', ja: 'Claude Pro の20倍の利用容量 — パワーユーザー級。複数の Claude Code を並列実行するのに最適で、最優先と全モデル・全機能へのフルアクセス。単独パワーユーザーに最良の選択とされます。', ru: 'В 20 раз больше использования, чем Claude Pro — класс профи. Идеально для параллельного запуска нескольких Claude Code, высший приоритет и полный доступ ко всем моделям. Лучшее предложение для одного профи.', ms: 'Kapasiti penggunaan 20x ganda Claude Pro — kelas pengguna kuasa. Sesuai untuk menjalankan beberapa Claude Code selari, dengan keutamaan tertinggi dan akses penuh semua model & ciri.', hi: 'Claude Pro से 20 गुना अधिक उपयोग क्षमता — पावर-यूज़र क्लास। कई Claude Code इंस्टेंस समानांतर चलाने के लिए आदर्श, सर्वोच्च प्राथमिकता और सभी मॉडल व सुविधाओं तक पूर्ण पहुंच।', de: '20-fache Nutzungskapazität gegenüber Claude Pro — Power-User-Klasse. Ideal für mehrere parallele Claude-Code-Instanzen, mit höchster Priorität und vollem Zugang zu allen Modellen.', vi: 'Dung lượng gấp 20 lần Claude Pro — hạng nâng cao. Lý tưởng để chạy nhiều Claude Code song song, ưu tiên cao nhất và toàn quyền mọi mô hình & tính năng.' },
    features: {
      en: ['20x more usage than Claude Pro', 'Run several Claude Code instances in parallel', 'Top priority of all tiers', 'Full access to all models & features'],
      zh: ['使用量是 Claude Pro 的 20 倍', '并行运行多个 Claude Code 实例', '所有套餐中最高优先级', '完整访问所有模型与功能'],
      ja: ['Claude Pro の20倍の利用量', '複数の Claude Code を並列実行', '全プラン中で最優先', '全モデル・全機能にフルアクセス'],
      ru: ['В 20 раз больше использования, чем Claude Pro', 'Несколько Claude Code параллельно', 'Высший приоритет среди тарифов', 'Полный доступ ко всем моделям и функциям'],
      ms: ['Penggunaan 20x ganda Claude Pro', 'Jalankan beberapa Claude Code selari', 'Keutamaan tertinggi antara semua tier', 'Akses penuh semua model & ciri'],
      hi: ['Claude Pro से 20 गुना अधिक उपयोग', 'कई Claude Code इंस्टेंस समानांतर चलाएं', 'सभी टियर में सर्वोच्च प्राथमिकता', 'सभी मॉडल व सुविधाओं तक पूर्ण पहुंच'],
      de: ['20x mehr Nutzung als Claude Pro', 'Mehrere Claude-Code-Instanzen parallel', 'Höchste Priorität aller Stufen', 'Voller Zugang zu allen Modellen & Funktionen'],
      vi: ['Sử dụng gấp 20 lần Claude Pro', 'Chạy nhiều Claude Code song song', 'Ưu tiên cao nhất trong các gói', 'Toàn quyền mọi mô hình & tính năng'],
    },
  },
  'google-ai-pro': {
    tagline: { en: 'Gemini 3 Pro with full Google ecosystem integration.', zh: 'Gemini 3 Pro，全面集成 Google 生态系统。', ja: 'Google エコシステムと完全統合した Gemini 3 Pro。', ru: 'Gemini 3 Pro с полной интеграцией экосистемы Google.', ms: 'Gemini 3 Pro dengan integrasi penuh ekosistem Google.', hi: 'पूर्ण Google इकोसिस्टम एकीकरण के साथ Gemini 3 Pro।', de: 'Gemini 3 Pro mit voller Integration des Google-Ökosystems.', vi: 'Gemini 3 Pro tích hợp đầy đủ hệ sinh thái Google.' },
    description: { en: 'Full access to Gemini 3 Pro with advanced features like Deep Research and Nano Banana Pro. Higher quota than the free tier, Gmail/Docs/Workspace integration, a YouTube Premium Lite bonus, and large Google One storage. Available as 12- and 18-month plans.', zh: '完整访问 Gemini 3 Pro，含 Deep Research 和 Nano Banana Pro 等高级功能。比免费版更高的配额，集成 Gmail/Docs/Workspace，赠送 YouTube Premium Lite，以及大容量 Google One 存储。提供 12 个月和 18 个月套餐。', ja: 'Deep Research や Nano Banana Pro などの高度な機能を備えた Gemini 3 Pro にフルアクセス。無料枠より多いクォータ、Gmail/Docs/Workspace 連携、YouTube Premium Lite 特典、大容量の Google One ストレージ。12・18か月プランを用意。', ru: 'Полный доступ к Gemini 3 Pro с функциями Deep Research и Nano Banana Pro. Больше квоты, чем в бесплатной версии, интеграция Gmail/Docs/Workspace, бонус YouTube Premium Lite и большое хранилище Google One. Планы на 12 и 18 месяцев.', ms: 'Akses penuh Gemini 3 Pro dengan ciri lanjutan seperti Deep Research dan Nano Banana Pro. Kuota lebih tinggi, integrasi Gmail/Docs/Workspace, bonus YouTube Premium Lite, dan storan Google One besar. Tersedia pakej 12 & 18 bulan.', hi: 'Deep Research और Nano Banana Pro जैसी उन्नत सुविधाओं के साथ Gemini 3 Pro तक पूर्ण पहुंच। फ्री टियर से अधिक कोटा, Gmail/Docs/Workspace एकीकरण, YouTube Premium Lite बोनस, और बड़ा Google One स्टोरेज। 12 और 18 महीने की योजनाएं।', de: 'Voller Zugang zu Gemini 3 Pro mit Deep Research und Nano Banana Pro. Höheres Kontingent als die Gratis-Stufe, Gmail/Docs/Workspace-Integration, YouTube-Premium-Lite-Bonus und großer Google-One-Speicher. Als 12- und 18-Monats-Pläne.', vi: 'Toàn quyền truy cập Gemini 3 Pro với Deep Research và Nano Banana Pro. Hạn mức cao hơn bản miễn phí, tích hợp Gmail/Docs/Workspace, tặng YouTube Premium Lite và bộ nhớ Google One lớn. Có gói 12 và 18 tháng.' },
    features: {
      en: ['Gemini 3 Pro + Deep Research & Nano Banana Pro', 'Gmail, Docs & Workspace integration', 'YouTube Premium Lite bonus', 'Large Google One storage'],
      zh: ['Gemini 3 Pro + Deep Research 和 Nano Banana Pro', '集成 Gmail、Docs 和 Workspace', '赠送 YouTube Premium Lite', '大容量 Google One 存储'],
      ja: ['Gemini 3 Pro + Deep Research と Nano Banana Pro', 'Gmail・Docs・Workspace 連携', 'YouTube Premium Lite 特典', '大容量 Google One ストレージ'],
      ru: ['Gemini 3 Pro + Deep Research и Nano Banana Pro', 'Интеграция Gmail, Docs и Workspace', 'Бонус YouTube Premium Lite', 'Большое хранилище Google One'],
      ms: ['Gemini 3 Pro + Deep Research & Nano Banana Pro', 'Integrasi Gmail, Docs & Workspace', 'Bonus YouTube Premium Lite', 'Storan Google One besar'],
      hi: ['Gemini 3 Pro + Deep Research और Nano Banana Pro', 'Gmail, Docs और Workspace एकीकरण', 'YouTube Premium Lite बोनस', 'बड़ा Google One स्टोरेज'],
      de: ['Gemini 3 Pro + Deep Research & Nano Banana Pro', 'Gmail-, Docs- & Workspace-Integration', 'YouTube-Premium-Lite-Bonus', 'Großer Google-One-Speicher'],
      vi: ['Gemini 3 Pro + Deep Research & Nano Banana Pro', 'Tích hợp Gmail, Docs & Workspace', 'Tặng YouTube Premium Lite', 'Bộ nhớ Google One lớn'],
    },
  },
  'google-ai-ultra': {
    tagline: { en: 'Top Gemini limits + Veo, Deep Think, and agentic tools.', zh: '最高 Gemini 额度 + Veo、Deep Think 和智能体工具。', ja: '最高クラスの Gemini 上限 + Veo、Deep Think、エージェントツール。', ru: 'Максимальные лимиты Gemini + Veo, Deep Think и агентные инструменты.', ms: 'Had Gemini tertinggi + Veo, Deep Think & alat agentik.', hi: 'सर्वोच्च Gemini सीमाएं + Veo, Deep Think और एजेंटिक टूल।', de: 'Höchste Gemini-Limits + Veo, Deep Think und Agenten-Tools.', vi: 'Giới hạn Gemini cao nhất + Veo, Deep Think và công cụ agentic.' },
    description: { en: '5x higher usage limits than AI Pro (up to 20x on the top tier). Early access to advanced features: Deep Think, Gemini Spark, Veo for video generation, and Flow. Includes 20 TB storage, YouTube Premium Lite, and agentic tools like Project Mariner.', zh: '使用额度比 AI Pro 高 5 倍（顶级套餐高达 20 倍）。抢先体验高级功能：Deep Think、Gemini Spark、用于视频生成的 Veo 和 Flow。含 20 TB 存储、YouTube Premium Lite 和 Project Mariner 等智能体工具。', ja: 'AI Pro より5倍（最上位で最大20倍）高い利用上限。Deep Think、Gemini Spark、動画生成の Veo、Flow を先行利用。20TB ストレージ、YouTube Premium Lite、Project Mariner などのエージェントツールを含む。', ru: 'Лимиты в 5 раз выше, чем у AI Pro (до 20x на топ-тарифе). Ранний доступ к Deep Think, Gemini Spark, Veo для генерации видео и Flow. Включает 20 ТБ хранилища, YouTube Premium Lite и агентные инструменты вроде Project Mariner.', ms: 'Had penggunaan 5x lebih tinggi daripada AI Pro (sehingga 20x pada tier teratas). Akses awal Deep Think, Gemini Spark, Veo untuk penjanaan video & Flow. Termasuk storan 20 TB, YouTube Premium Lite & alat agentik seperti Project Mariner.', hi: 'AI Pro से 5 गुना अधिक उपयोग सीमाएं (शीर्ष टियर पर 20 गुना तक)। उन्नत सुविधाओं तक प्रारंभिक पहुंच: Deep Think, Gemini Spark, वीडियो जनरेशन के लिए Veo, और Flow। 20 TB स्टोरेज, YouTube Premium Lite, और Project Mariner जैसे एजेंटिक टूल शामिल।', de: '5x höhere Nutzungslimits als AI Pro (bis zu 20x in der Top-Stufe). Früher Zugang zu Deep Think, Gemini Spark, Veo für Videogenerierung und Flow. Mit 20 TB Speicher, YouTube Premium Lite und Agenten-Tools wie Project Mariner.', vi: 'Giới hạn cao gấ 5 lần AI Pro (đến 20x ở gói cao nhất). Truy cập sớm Deep Think, Gemini Spark, Veo tạo video và Flow. Gồm 20 TB lưu trữ, YouTube Premium Lite và công cụ agentic như Project Mariner.' },
    features: {
      en: ['5x–20x higher limits than AI Pro', 'Deep Think, Gemini Spark, Veo & Flow', '20 TB storage + YouTube Premium Lite', 'Agentic tools (Project Mariner / Agent Mode)'],
      zh: ['额度比 AI Pro 高 5–20 倍', 'Deep Think、Gemini Spark、Veo 和 Flow', '20 TB 存储 + YouTube Premium Lite', '智能体工具（Project Mariner / Agent Mode）'],
      ja: ['AI Pro より5〜20倍高い上限', 'Deep Think、Gemini Spark、Veo、Flow', '20TB ストレージ + YouTube Premium Lite', 'エージェントツール（Project Mariner / Agent Mode）'],
      ru: ['Лимиты в 5–20 раз выше AI Pro', 'Deep Think, Gemini Spark, Veo и Flow', '20 ТБ хранилища + YouTube Premium Lite', 'Агентные инструменты (Project Mariner / Agent Mode)'],
      ms: ['Had 5x–20x lebih tinggi daripada AI Pro', 'Deep Think, Gemini Spark, Veo & Flow', 'Storan 20 TB + YouTube Premium Lite', 'Alat agentik (Project Mariner / Agent Mode)'],
      hi: ['AI Pro से 5x–20x अधिक सीमाएं', 'Deep Think, Gemini Spark, Veo और Flow', '20 TB स्टोरेज + YouTube Premium Lite', 'एजेंटिक टूल (Project Mariner / Agent Mode)'],
      de: ['5x–20x höhere Limits als AI Pro', 'Deep Think, Gemini Spark, Veo & Flow', '20 TB Speicher + YouTube Premium Lite', 'Agenten-Tools (Project Mariner / Agent Mode)'],
      vi: ['Giới hạn cao gấp 5x–20x AI Pro', 'Deep Think, Gemini Spark, Veo & Flow', '20 TB lưu trữ + YouTube Premium Lite', 'Công cụ agentic (Project Mariner / Agent Mode)'],
    },
  },
  'chatgpt-plus': {
    tagline: { en: 'GPT-5.5 access with high limits, Sora, and Agent Mode.', zh: '访问 GPT-5.5，高额度，含 Sora 和 Agent Mode。', ja: '高い上限・Sora・Agent Mode 付きの GPT-5.5 アクセス。', ru: 'Доступ к GPT-5.5 с высокими лимитами, Sora и Agent Mode.', ms: 'Akses GPT-5.5 dengan had tinggi, Sora & Agent Mode.', hi: 'उच्च सीमा, Sora और Agent Mode के साथ GPT-5.5 एक्सेस।', de: 'GPT-5.5-Zugang mit hohen Limits, Sora und Agent Mode.', vi: 'Truy cập GPT-5.5 với giới hạn cao, Sora và Agent Mode.' },
    description: { en: 'Access GPT-5.5 (the default flagship model) with high weekly limits and no ads. Includes Deep Research (10 runs/month), Sora for video, Codex, Agent Mode, image generation 2.0, advanced voice mode, Custom GPTs, and a large context window (~320 pages of text).', zh: '访问 GPT-5.5（默认旗舰模型），高周限额且无广告。含 Deep Research（每月 10 次）、用于视频的 Sora、Codex、Agent Mode、图像生成 2.0、高级语音模式、自定义 GPTs，以及大上下文窗口（约 320 页文本）。', ja: 'GPT-5.5（既定のフラッグシップ）に高い週次上限・広告なしでアクセス。Deep Research（月10回）、動画の Sora、Codex、Agent Mode、画像生成2.0、高度な音声モード、Custom GPTs、大きなコンテキスト（約320ページ）を含む。', ru: 'Доступ к GPT-5.5 (флагман по умолчанию) с высокими недельными лимитами и без рекламы. Включает Deep Research (10 запусков/мес), Sora для видео, Codex, Agent Mode, генерацию изображений 2.0, продвинутый голосовой режим, Custom GPTs и большой контекст (~320 страниц).', ms: 'Akses GPT-5.5 (model utama lalai) dengan had mingguan tinggi tanpa iklan. Termasuk Deep Research (10 kali/bulan), Sora untuk video, Codex, Agent Mode, penjanaan imej 2.0, mod suara lanjutan, Custom GPTs & tetingkap konteks besar (~320 halaman).', hi: 'उच्च साप्ताहिक सीमा और बिना विज्ञापन के GPT-5.5 (डिफ़ॉल्ट फ्लैगशिप) एक्सेस। Deep Research (10 रन/माह), वीडियो के लिए Sora, Codex, Agent Mode, इमेज जनरेशन 2.0, उन्नत वॉइस मोड, Custom GPTs, और बड़ी कॉन्टेक्स्ट विंडो (~320 पृष्ठ)।', de: 'Zugang zu GPT-5.5 (Standard-Flaggschiff) mit hohen Wochenlimits und ohne Werbung. Mit Deep Research (10 Läufe/Monat), Sora für Video, Codex, Agent Mode, Bildgenerierung 2.0, erweitertem Sprachmodus, Custom GPTs und großem Kontext (~320 Seiten).', vi: 'Truy cập GPT-5.5 (mô hình hàng đầu mặc định) với giới hạn tuần cao và không quảng cáo. Gồm Deep Research (10 lần/tháng), Sora cho video, Codex, Agent Mode, tạo ảnh 2.0, chế độ giọng nói nâng cao, Custom GPTs và cửa sổ ngữ cảnh lớn (~320 trang).' },
    features: {
      en: ['GPT-5.5 flagship, high weekly limits, ad-free', 'Deep Research, Sora (video), Codex & Agent Mode', 'Image generation 2.0 + advanced voice mode', 'Context window ~320 pages per chat'],
      zh: ['GPT-5.5 旗舰，高周限额，无广告', 'Deep Research、Sora（视频）、Codex 和 Agent Mode', '图像生成 2.0 + 高级语音模式', '上下文窗口约 320 页/对话'],
      ja: ['GPT-5.5 フラッグシップ、高い週次上限、広告なし', 'Deep Research、Sora（動画）、Codex、Agent Mode', '画像生成2.0 + 高度な音声モード', 'コンテキスト約320ページ/会話'],
      ru: ['Флагман GPT-5.5, высокие недельные лимиты, без рекламы', 'Deep Research, Sora (видео), Codex и Agent Mode', 'Генерация изображений 2.0 + голосовой режим', 'Контекст ~320 страниц на чат'],
      ms: ['GPT-5.5 utama, had mingguan tinggi, tanpa iklan', 'Deep Research, Sora (video), Codex & Agent Mode', 'Penjanaan imej 2.0 + mod suara lanjutan', 'Tetingkap konteks ~320 halaman setiap sembang'],
      hi: ['GPT-5.5 फ्लैगशिप, उच्च साप्ताहिक सीमा, बिना विज्ञापन', 'Deep Research, Sora (वीडियो), Codex और Agent Mode', 'इमेज जनरेशन 2.0 + उन्नत वॉइस मोड', 'कॉन्टेक्स्ट विंडो ~320 पृष्ठ/चैट'],
      de: ['GPT-5.5-Flaggschiff, hohe Wochenlimits, werbefrei', 'Deep Research, Sora (Video), Codex & Agent Mode', 'Bildgenerierung 2.0 + erweiterter Sprachmodus', 'Kontextfenster ~320 Seiten pro Chat'],
      vi: ['GPT-5.5 hàng đầu, giới hạn tuần cao, không quảng cáo', 'Deep Research, Sora (video), Codex & Agent Mode', 'Tạo ảnh 2.0 + chế độ giọng nói nâng cao', 'Cửa sổ ngữ cảnh ~320 trang mỗi cuộc trò chuyện'],
    },
  },
  'chatgpt-pro': {
    tagline: { en: 'GPT-5.5 Pro for the most complex professional work.', zh: '用于最复杂专业工作的 GPT-5.5 Pro。', ja: '最も複雑な業務向けの GPT-5.5 Pro。', ru: 'GPT-5.5 Pro для самых сложных профессиональных задач.', ms: 'GPT-5.5 Pro untuk kerja profesional paling kompleks.', hi: 'सबसे जटिल पेशेवर कार्य के लिए GPT-5.5 Pro।', de: 'GPT-5.5 Pro für die anspruchsvollste Profiarbeit.', vi: 'GPT-5.5 Pro cho công việc chuyên môn phức tạp nhất.' },
    description: { en: 'Access GPT-5.5 Pro for the most complex professional work. Limits of 5x ($100 tier) or 20x ($200 tier) versus Plus, with a context window up to 1M tokens, Deep Research up to 250 runs/month, and no caps on file uploads or image creation.', zh: '访问 GPT-5.5 Pro，应对最复杂的专业工作。相比 Plus 提供 5 倍（$100 套餐）或 20 倍（$200 套餐）额度，上下文窗口高达 100 万 token，Deep Research 每月最多 250 次，文件上传与图像创建无上限。', ja: '最も複雑な業務向けに GPT-5.5 Pro を利用。Plus 比で5倍（$100）または20倍（$200）の上限、最大100万トークンのコンテキスト、Deep Research 月250回、ファイルアップロードと画像生成は上限なし。', ru: 'Доступ к GPT-5.5 Pro для самых сложных задач. Лимиты 5x ($100) или 20x ($200) против Plus, контекст до 1 млн токенов, Deep Research до 250 запусков/мес и без ограничений на загрузку файлов и генерацию изображений.', ms: 'Akses GPT-5.5 Pro untuk kerja paling kompleks. Had 5x ($100) atau 20x ($200) berbanding Plus, tetingkap konteks sehingga 1J token, Deep Research sehingga 250 kali/bulan, tanpa had muat naik fail & penciptaan imej.', hi: 'सबसे जटिल पेशेवर कार्य के लिए GPT-5.5 Pro। Plus की तुलना में 5x ($100) या 20x ($200) सीमाएं, 1M टोकन तक कॉन्टेक्स्ट विंडो, Deep Research 250 रन/माह तक, और फ़ाइल अपलोड व इमेज निर्माण पर कोई सीमा नहीं।', de: 'GPT-5.5 Pro für die komplexeste Profiarbeit. Limits von 5x ($100) oder 20x ($200) gegenüber Plus, Kontext bis 1 Mio. Token, Deep Research bis 250 Läufe/Monat und keine Caps bei Datei-Uploads oder Bilderstellung.', vi: 'GPT-5.5 Pro cho công việc phức tạp nhất. Giới hạn 5x ($100) hoặc 20x ($200) so với Plus, ngữ cảnh tới 1M token, Deep Research tới 250 lần/tháng và không giới hạn tải tệp hay tạo ảnh.' },
    features: {
      en: ['GPT-5.5 Pro for the hardest work', 'Limits 5x ($100) or 20x ($200) vs Plus', 'Context window up to 1M tokens', 'Deep Research up to 250 runs/month'],
      zh: ['GPT-5.5 Pro 应对最难任务', '相比 Plus 5 倍（$100）或 20 倍（$200）额度', '上下文窗口高达 100 万 token', 'Deep Research 每月最多 250 次'],
      ja: ['最難の業務向け GPT-5.5 Pro', 'Plus 比 5倍（$100）/20倍（$200）の上限', '最大100万トークンのコンテキスト', 'Deep Research 月250回'],
      ru: ['GPT-5.5 Pro для сложнейших задач', 'Лимиты 5x ($100) или 20x ($200) против Plus', 'Контекст до 1 млн токенов', 'Deep Research до 250 запусков/мес'],
      ms: ['GPT-5.5 Pro untuk kerja paling sukar', 'Had 5x ($100) atau 20x ($200) vs Plus', 'Tetingkap konteks sehingga 1J token', 'Deep Research sehingga 250 kali/bulan'],
      hi: ['सबसे कठिन कार्य के लिए GPT-5.5 Pro', 'Plus की तुलना में 5x ($100) या 20x ($200)', '1M टोकन तक कॉन्टेक्स्ट विंडो', 'Deep Research 250 रन/माह तक'],
      de: ['GPT-5.5 Pro für anspruchsvollste Arbeit', 'Limits 5x ($100) oder 20x ($200) ggü. Plus', 'Kontextfenster bis 1 Mio. Token', 'Deep Research bis 250 Läufe/Monat'],
      vi: ['GPT-5.5 Pro cho công việc khó nhất', 'Giới hạn 5x ($100) hoặc 20x ($200) so với Plus', 'Ngữ cảnh tới 1M token', 'Deep Research tới 250 lần/tháng'],
    },
  },
  'kiro-ai': {
    tagline: { en: 'Spec-driven AI IDE powered by Opus 4.8 from AWS.', zh: '由 AWS Opus 4.8 驱动的规范驱动型 AI IDE。', ja: 'AWS の Opus 4.8 を搭載した仕様駆動型 AI IDE。', ru: 'Spec-driven AI IDE на базе Opus 4.8 от AWS.', ms: 'IDE AI dipacu spesifikasi berkuasa Opus 4.8 daripada AWS.', hi: 'AWS के Opus 4.8 द्वारा संचालित स्पेक-ड्रिवन AI IDE।', de: 'Spec-getriebene KI-IDE mit Opus 4.8 von AWS.', vi: 'IDE AI hướng đặc tả, vận hành bởi Opus 4.8 của AWS.' },
    description: { en: 'A spec-driven AI IDE that brings engineering rigor to AI coding. Comes with agent hooks to automate tests, docs, and scans on events, a pay-as-you-go system ($0.04/credit) so work never stops abruptly, and full access to Opus 4.8.', zh: '规范驱动的 AI IDE，为 AI 编程带来工程严谨性。配备 agent hooks，在事件触发时自动执行测试、文档和扫描；采用按量付费（$0.04/积分），让工作不会突然中断；完整访问 Opus 4.8。', ja: 'AI コーディングにエンジニアリングの厳密さをもたらす仕様駆動型 AI IDE。イベント時にテスト・ドキュメント・スキャンを自動化する agent hooks、作業が急に止まらない従量課金（$0.04/クレジット）、Opus 4.8 へのフルアクセスを搭載。', ru: 'Spec-driven AI IDE, привносящий инженерную строгость в AI-кодинг. Agent hooks для автоматизации тестов, документации и сканов по событиям, оплата по факту ($0,04/кредит), чтобы работа не прерывалась, и полный доступ к Opus 4.8.', ms: 'IDE AI dipacu spesifikasi yang membawa ketelitian kejuruteraan ke pengekodan AI. Dilengkapi agent hooks untuk automasi ujian, dokumentasi & imbasan pada peristiwa, sistem bayar ikut guna ($0.04/kredit) supaya kerja tidak terhenti, dan akses penuh Opus 4.8.', hi: 'एक स्पेक-ड्रिवन AI IDE जो AI कोडिंग में इंजीनियरिंग कठोरता लाता है। इवेंट पर टेस्ट, डॉक्स और स्कैन स्वचालित करने हेतु agent hooks, पे-एज़-यू-गो ($0.04/क्रेडिट) ताकि काम अचानक न रुके, और Opus 4.8 तक पूर्ण पहुंच।', de: 'Eine spec-getriebene KI-IDE, die Engineering-Disziplin ins AI-Coding bringt. Mit Agent-Hooks zur Automatisierung von Tests, Docs und Scans bei Events, Pay-as-you-go ($0,04/Credit), damit die Arbeit nie abrupt stoppt, und vollem Zugang zu Opus 4.8.', vi: 'IDE AI hướng đặc tả mang sự nghiêm ngặt kỹ thuật vào lập trình AI. Có agent hooks tự động hóa kiểm thử, tài liệu và quét theo sự kiện, trả theo dùng ($0.04/tín dụng) để công việc không dừng đột ngột, và toàn quyền Opus 4.8.' },
    features: {
      en: ['Spec-driven workflow — engineering rigor for AI coding', 'Agent hooks: automate tests, docs & scans', 'Pay-as-you-go $0.04/credit, work never stops', 'Full access to Opus 4.8'],
      zh: ['规范驱动工作流 — 为 AI 编程带来工程严谨性', 'Agent hooks：自动化测试、文档和扫描', '按量付费 $0.04/积分，工作不中断', '完整访问 Opus 4.8'],
      ja: ['仕様駆動ワークフロー — AI コーディングに厳密性', 'agent hooks：テスト・ドキュメント・スキャンを自動化', '従量課金 $0.04/クレジット、作業が止まらない', 'Opus 4.8 にフルアクセス'],
      ru: ['Spec-driven процесс — инженерная строгость для AI-кода', 'Agent hooks: автоматизация тестов, документации и сканов', 'Оплата по факту $0,04/кредит, работа не прерывается', 'Полный доступ к Opus 4.8'],
      ms: ['Aliran kerja dipacu spesifikasi — ketelitian kejuruteraan', 'Agent hooks: automasi ujian, dokumentasi & imbasan', 'Bayar ikut guna $0.04/kredit, kerja tak terhenti', 'Akses penuh Opus 4.8'],
      hi: ['स्पेक-ड्रिवन वर्कफ़्लो — AI कोडिंग के लिए इंजीनियरिंग कठोरता', 'Agent hooks: टेस्ट, डॉक्स और स्कैन स्वचालित', 'पे-एज़-यू-गो $0.04/क्रेडिट, काम नहीं रुकता', 'Opus 4.8 तक पूर्ण पहुंच'],
      de: ['Spec-getriebener Workflow — Engineering-Disziplin', 'Agent-Hooks: Tests, Docs & Scans automatisieren', 'Pay-as-you-go $0,04/Credit, Arbeit stoppt nie', 'Voller Zugang zu Opus 4.8'],
      vi: ['Quy trình hướng đặc tả — nghiêm ngặt kỹ thuật', 'Agent hooks: tự động kiểm thử, tài liệu & quét', 'Trả theo dùng $0.04/tín dụng, không dừng', 'Toàn quyền Opus 4.8'],
    },
  },
  'api-deepseek': {
    tagline: { en: 'Pay per request — cheapest API, follows DeepSeek off-peak discounts.', zh: '按请求付费 — 最便宜的 API，跟随 DeepSeek 低峰折扣。', ja: 'リクエスト課金 — 最安級 API、DeepSeek のオフピーク割引に連動。', ru: 'Оплата за запрос — дешёвый API, со скидками DeepSeek в непиковые часы.', ms: 'Bayar setiap permintaan — API termurah, ikut diskaun luar puncak DeepSeek.', hi: 'प्रति अनुरोध भुगतान — सबसे सस्ता API, DeepSeek ऑफ-पीक छूट के अनुसार।', de: 'Pay per Request — günstigste API, folgt DeepSeek-Off-Peak-Rabatten.', vi: 'Trả theo yêu cầu — API rẻ nhất, theo giảm giá giờ thấp điểm của DeepSeek.' },
    description: { en: 'A DeepSeek API key billed per request, not an expensive subscription. One of the cheapest APIs on the market, automatically following DeepSeek off-peak discounts (50–75% savings at certain hours). 1M-token context, thinking & non-thinking modes, plus automatic context caching that lowers per-request cost.', zh: '按请求计费的 DeepSeek API 密钥，而非昂贵订阅。市场上最便宜的 API 之一，自动跟随 DeepSeek 低峰折扣（特定时段省 50–75%）。100 万 token 上下文，思考与非思考模式，以及自动上下文缓存降低每次请求成本。', ja: '高額なサブスクではなく、リクエスト課金の DeepSeek API キー。市場最安級で、DeepSeek のオフピーク割引（特定時間に50〜75%節約）に自動連動。100万トークンのコンテキスト、thinking/non-thinking モード、リクエストごとのコストを下げる自動コンテキストキャッシュ。', ru: 'API-ключ DeepSeek с оплатой за запрос, а не дорогая подписка. Один из самых дешёвых API, автоматически со скидками DeepSeek в непиковые часы (экономия 50–75%). Контекст 1 млн токенов, режимы thinking/non-thinking и авто-кэширование контекста.', ms: 'Kunci API DeepSeek dicaj setiap permintaan, bukan langganan mahal. Antara API termurah, ikut diskaun luar puncak DeepSeek (jimat 50–75% pada waktu tertentu). Konteks 1J token, mod thinking & non-thinking, serta cache konteks automatik.', hi: 'महंगी सदस्यता नहीं, प्रति अनुरोध बिल किया गया DeepSeek API कुंजी। बाज़ार के सबसे सस्ते API में से एक, DeepSeek ऑफ-पीक छूट (कुछ घंटों में 50–75% बचत) के अनुसार स्वतः। 1M टोकन कॉन्टेक्स्ट, thinking व non-thinking मोड, और स्वचालित कॉन्टेक्स्ट कैशिंग।', de: 'Ein DeepSeek-API-Schlüssel pro Request statt teurem Abo. Eine der günstigsten APIs, folgt automatisch DeepSeek-Off-Peak-Rabatten (50–75% zu bestimmten Zeiten). 1-Mio-Token-Kontext, Thinking-/Non-Thinking-Modus und automatisches Kontext-Caching.', vi: 'Khóa API DeepSeek tính phí theo yêu cầu, không phải gói đắt. Một trong những API rẻ nhất, tự động theo giảm giá giờ thấp điểm DeepSeek (tiết kiệm 50–75% vào giờ nhất định). Ngữ cảnh 1M token, chế độ thinking & non-thinking, tự động cache ngữ cảnh.' },
    features: {
      en: ['Per-request pricing — starts at a few dollars', 'Follows DeepSeek off-peak discounts (50–75% off)', 'Automatic context caching cuts costs', '1M-token context, thinking & non-thinking modes'],
      zh: ['按请求定价 — 几美元起', '跟随 DeepSeek 低峰折扣（省 50–75%）', '自动上下文缓存降低成本', '100 万 token 上下文，思考与非思考模式'],
      ja: ['リクエスト課金 — 数ドルから', 'DeepSeek オフピーク割引に連動（50〜75%オフ）', '自動コンテキストキャッシュでコスト削減', '100万トークン、thinking/non-thinking モード'],
      ru: ['Оплата за запрос — от нескольких долларов', 'Скидки DeepSeek в непик (50–75%)', 'Авто-кэш контекста снижает затраты', 'Контекст 1М токенов, режимы thinking/non-thinking'],
      ms: ['Harga setiap permintaan — bermula beberapa dolar', 'Ikut diskaun luar puncak DeepSeek (50–75%)', 'Cache konteks automatik kurangkan kos', 'Konteks 1J token, mod thinking & non-thinking'],
      hi: ['प्रति-अनुरोध मूल्य — कुछ डॉलर से', 'DeepSeek ऑफ-पीक छूट (50–75% तक)', 'स्वचालित कॉन्टेक्स्ट कैशिंग लागत घटाए', '1M टोकन कॉन्टेक्स्ट, thinking व non-thinking मोड'],
      de: ['Preis pro Request — ab wenigen Dollar', 'Folgt DeepSeek-Off-Peak-Rabatten (50–75%)', 'Automatisches Kontext-Caching senkt Kosten', '1-Mio-Token-Kontext, Thinking-/Non-Thinking-Modus'],
      vi: ['Giá theo yêu cầu — từ vài đô', 'Theo giảm giá giờ thấp điểm DeepSeek (50–75%)', 'Tự động cache ngữ cảnh giảm chi phí', 'Ngữ cảnh 1M token, chế độ thinking & non-thinking'],
    },
  },
  'api-openai': {
    tagline: { en: 'Pay per request — save with cached input & OpenAI Batch API.', zh: '按请求付费 — 借助缓存输入和 OpenAI Batch API 省钱。', ja: 'リクエスト課金 — キャッシュ入力と OpenAI Batch API で節約。', ru: 'Оплата за запрос — экономия с кэшем ввода и OpenAI Batch API.', ms: 'Bayar setiap permintaan — jimat dengan input cache & OpenAI Batch API.', hi: 'प्रति अनुरोध भुगतान — कैश्ड इनपुट और OpenAI Batch API से बचत।', de: 'Pay per Request — sparen mit Cached Input & OpenAI Batch API.', vi: 'Trả theo yêu cầu — tiết kiệm với input cache & OpenAI Batch API.' },
    description: { en: 'An OpenAI API key billed per request, not an expensive subscription. Automatically follows OpenAI platform discounts: cached input saves up to 90% and the Batch API saves 50%. A full model ladder from GPT-5.4 Nano to GPT-5.5 Pro for flexible routing, with a context window up to 1.05M tokens.', zh: '按请求计费的 OpenAI API 密钥，而非昂贵订阅。自动跟随 OpenAI 平台折扣：缓存输入最多省 90%，Batch API 省 50%。从 GPT-5.4 Nano 到 GPT-5.5 Pro 的完整模型阶梯，灵活路由，上下文窗口高达 105 万 token。', ja: '高額なサブスクではなく、リクエスト課金の OpenAI API キー。OpenAI のプラットフォーム割引に自動連動：キャッシュ入力で最大90%、Batch API で50%節約。GPT-5.4 Nano から GPT-5.5 Pro までのモデルラダーで柔軟にルーティング、最大105万トークンのコンテキスト。', ru: 'API-ключ OpenAI с оплатой за запрос, а не дорогая подписка. Автоматически со скидками платформы OpenAI: кэш ввода экономит до 90%, Batch API — 50%. Полная линейка моделей от GPT-5.4 Nano до GPT-5.5 Pro и контекст до 1,05 млн токенов.', ms: 'Kunci API OpenAI dicaj setiap permintaan, bukan langganan mahal. Ikut diskaun platform OpenAI: input cache jimat sehingga 90% & Batch API jimat 50%. Tangga model penuh dari GPT-5.4 Nano ke GPT-5.5 Pro, konteks sehingga 1.05J token.', hi: 'महंगी सदस्यता नहीं, प्रति अनुरोध बिल किया गया OpenAI API कुंजी। OpenAI प्लेटफ़ॉर्म छूट के अनुसार स्वतः: कैश्ड इनपुट 90% तक और Batch API 50% बचाए। GPT-5.4 Nano से GPT-5.5 Pro तक पूरी मॉडल सीढ़ी, 1.05M टोकन तक कॉन्टेक्स्ट।', de: 'Ein OpenAI-API-Schlüssel pro Request statt teurem Abo. Folgt automatisch OpenAI-Plattformrabatten: Cached Input spart bis 90%, Batch API 50%. Volle Modellpalette von GPT-5.4 Nano bis GPT-5.5 Pro und Kontext bis 1,05 Mio. Token.', vi: 'Khóa API OpenAI tính phí theo yêu cầu, không phải gói đắt. Tự động theo giảm giá nền tảng OpenAI: input cache tiết kiệm tới 90% và Batch API 50%. Thang mô hình đầy đủ từ GPT-5.4 Nano đến GPT-5.5 Pro, ngữ cảnh tới 1.05M token.' },
    features: {
      en: ['Per-request pricing — pay for what you use', 'Cached input up to 90% off (follows platform)', 'Batch API saves 50% input & output', 'Model ladder GPT-5.4 Nano → GPT-5.5 Pro'],
      zh: ['按请求定价 — 按用量付费', '缓存输入最多省 90%（跟随平台）', 'Batch API 节省 50% 输入与输出', '模型阶梯 GPT-5.4 Nano → GPT-5.5 Pro'],
      ja: ['リクエスト課金 — 使った分だけ', 'キャッシュ入力で最大90%オフ（プラットフォーム連動）', 'Batch API で入出力50%節約', 'モデルラダー GPT-5.4 Nano → GPT-5.5 Pro'],
      ru: ['Оплата за запрос — платите за использование', 'Кэш ввода до 90% (по платформе)', 'Batch API экономит 50% ввода и вывода', 'Линейка GPT-5.4 Nano → GPT-5.5 Pro'],
      ms: ['Harga setiap permintaan — bayar ikut guna', 'Input cache sehingga 90% (ikut platform)', 'Batch API jimat 50% input & output', 'Tangga model GPT-5.4 Nano → GPT-5.5 Pro'],
      hi: ['प्रति-अनुरोध मूल्य — उपयोग अनुसार भुगतान', 'कैश्ड इनपुट 90% तक (प्लेटफ़ॉर्म अनुसार)', 'Batch API 50% इनपुट व आउटपुट बचाए', 'मॉडल सीढ़ी GPT-5.4 Nano → GPT-5.5 Pro'],
      de: ['Preis pro Request — zahlen nach Nutzung', 'Cached Input bis 90% (folgt Plattform)', 'Batch API spart 50% Ein- & Ausgabe', 'Modellpalette GPT-5.4 Nano → GPT-5.5 Pro'],
      vi: ['Giá theo yêu cầu — trả theo dùng', 'Input cache tới 90% (theo nền tảng)', 'Batch API tiết kiệm 50% input & output', 'Thang mô hình GPT-5.4 Nano → GPT-5.5 Pro'],
    },
  },
  'leonardo-ai-pro': {
    tagline: { en: 'Pro-class image generation + Seedance 2.0 access.', zh: '专业级图像生成 + Seedance 2.0 访问。', ja: 'プロ級の画像生成 + Seedance 2.0 アクセス。', ru: 'Генерация изображений профи-класса + доступ к Seedance 2.0.', ms: 'Penjanaan imej kelas pro + akses Seedance 2.0.', hi: 'प्रो-क्लास इमेज जनरेशन + Seedance 2.0 एक्सेस।', de: 'Bildgenerierung der Profi-Klasse + Seedance-2.0-Zugang.', vi: 'Tạo ảnh hạng pro + truy cập Seedance 2.0.' },
    description: { en: 'Leonardo AI Artisan tier (commonly called Pro) with 25,000 credits. Pro-class AI image generation: Phoenix, PhotoReal v2, Alchemy Refiner with no per-use fees, access to third-party video models including Seedance, Veo 3, Sora 2, and Kling, plus Consistent Character Engine, LoRA training, and Unified Canvas.', zh: 'Leonardo AI Artisan 套餐（通常称为 Pro），含 25,000 积分。专业级 AI 图像生成：Phoenix、PhotoReal v2、Alchemy Refiner，无按次费用；可访问 Seedance、Veo 3、Sora 2、Kling 等第三方视频模型；还有 Consistent Character Engine、LoRA 训练和 Unified Canvas。', ja: 'Leonardo AI の Artisan ティア（通称 Pro）、25,000 クレジット付き。プロ級の AI 画像生成：Phoenix、PhotoReal v2、Alchemy Refiner を都度課金なしで利用。Seedance、Veo 3、Sora 2、Kling などのサードパーティ動画モデルにアクセスでき、Consistent Character Engine、LoRA 学習、Unified Canvas も。', ru: 'Тариф Artisan от Leonardo AI (обычно называют Pro) с 25 000 кредитов. Генерация изображений профи-класса: Phoenix, PhotoReal v2, Alchemy Refiner без поштучной платы, доступ к видеомоделям Seedance, Veo 3, Sora 2, Kling, а также Consistent Character Engine, обучение LoRA и Unified Canvas.', ms: 'Tier Artisan Leonardo AI (biasa dipanggil Pro) dengan 25,000 kredit. Penjanaan imej AI kelas pro: Phoenix, PhotoReal v2, Alchemy Refiner tanpa bayaran setiap guna, akses model video pihak ketiga termasuk Seedance, Veo 3, Sora 2 & Kling, serta Consistent Character Engine, latihan LoRA & Unified Canvas.', hi: 'Leonardo AI Artisan टियर (आमतौर पर Pro कहा जाता है) 25,000 क्रेडिट के साथ। प्रो-क्लास AI इमेज जनरेशन: Phoenix, PhotoReal v2, Alchemy Refiner बिना प्रति-उपयोग शुल्क, Seedance, Veo 3, Sora 2, Kling सहित थर्ड-पार्टी वीडियो मॉडल तक पहुंच, साथ ही Consistent Character Engine, LoRA ट्रेनिंग और Unified Canvas।', de: 'Leonardo-AI-Artisan-Stufe (oft Pro genannt) mit 25.000 Credits. Bildgenerierung der Profi-Klasse: Phoenix, PhotoReal v2, Alchemy Refiner ohne Nutzungsgebühr, Zugang zu Drittanbieter-Videomodellen wie Seedance, Veo 3, Sora 2 und Kling, dazu Consistent Character Engine, LoRA-Training und Unified Canvas.', vi: 'Gói Artisan của Leonardo AI (thường gọi là Pro) với 25.000 tín dụng. Tạo ảnh AI hạng pro: Phoenix, PhotoReal v2, Alchemy Refiner không phí mỗi lần dùng, truy cập mô hình video bên thứ ba gồm Seedance, Veo 3, Sora 2, Kling, cùng Consistent Character Engine, huấn luyện LoRA và Unified Canvas.' },
    features: {
      en: ['Phoenix, PhotoReal v2 & Alchemy Refiner', 'Access Seedance, Veo 3, Sora 2 & Kling', 'Consistent Character Engine + LoRA training', 'Unified Canvas: inpainting & outpainting'],
      zh: ['Phoenix、PhotoReal v2 和 Alchemy Refiner', '访问 Seedance、Veo 3、Sora 2 和 Kling', 'Consistent Character Engine + LoRA 训练', 'Unified Canvas：内补与外扩'],
      ja: ['Phoenix、PhotoReal v2、Alchemy Refiner', 'Seedance、Veo 3、Sora 2、Kling にアクセス', 'Consistent Character Engine + LoRA 学習', 'Unified Canvas：インペイント＆アウトペイント'],
      ru: ['Phoenix, PhotoReal v2 и Alchemy Refiner', 'Доступ к Seedance, Veo 3, Sora 2 и Kling', 'Consistent Character Engine + обучение LoRA', 'Unified Canvas: inpainting и outpainting'],
      ms: ['Phoenix, PhotoReal v2 & Alchemy Refiner', 'Akses Seedance, Veo 3, Sora 2 & Kling', 'Consistent Character Engine + latihan LoRA', 'Unified Canvas: inpainting & outpainting'],
      hi: ['Phoenix, PhotoReal v2 और Alchemy Refiner', 'Seedance, Veo 3, Sora 2 और Kling तक पहुंच', 'Consistent Character Engine + LoRA ट्रेनिंग', 'Unified Canvas: इनपेंटिंग व आउटपेंटिंग'],
      de: ['Phoenix, PhotoReal v2 & Alchemy Refiner', 'Zugang zu Seedance, Veo 3, Sora 2 & Kling', 'Consistent Character Engine + LoRA-Training', 'Unified Canvas: Inpainting & Outpainting'],
      vi: ['Phoenix, PhotoReal v2 & Alchemy Refiner', 'Truy cập Seedance, Veo 3, Sora 2 & Kling', 'Consistent Character Engine + huấn luyện LoRA', 'Unified Canvas: inpainting & outpainting'],
    },
  },
  cursor: {
    tagline: { en: 'The fastest AI code editor with smart Agent & tab completion.', zh: '最快的 AI 代码编辑器，配备智能 Agent 与 Tab 补全。', ja: 'スマートなAgentとタブ補完を備えた最速のAIコードエディタ。', ru: 'Самый быстрый AI-редактор кода с умным Agent и tab-автодополнением.', ms: 'Editor kod AI terpantas dengan Agent pintar & pelengkapan tab.', hi: 'स्मार्ट Agent और टैब पूर्णता के साथ सबसे तेज़ AI कोड एडिटर।', de: 'Der schnellste KI-Code-Editor mit smartem Agent & Tab-Vervollständigung.', vi: 'Trình soạn mã AI nhanh nhất với Agent thông minh & tab completion.' },
    description: { en: 'Cursor is an AI code editor (built on VS Code) with super-fast tab completion, an Agent mode that completes multi-file tasks automatically, and access to frontier models (Claude, GPT, Gemini). Each paid plan includes a monthly credit pool for premium-model usage equal to the plan price.', zh: 'Cursor 是基于 VS Code 的 AI 代码编辑器，拥有超快 Tab 补全、可自动完成跨文件任务的 Agent 模式，以及对前沿模型（Claude、GPT、Gemini）的访问。每个付费套餐都含与套餐价格等额的高级模型用量额度。', ja: 'Cursor は VS Code ベースの AI コードエディタで、超高速タブ補完、複数ファイルのタスクを自動で行う Agent モード、フロンティアモデル（Claude、GPT、Gemini）へのアクセスを備えます。各有料プランにはプラン価格と同額のプレミアムモデル利用クレジットが含まれます。', ru: 'Cursor — AI-редактор кода на базе VS Code: сверхбыстрое tab-автодополнение, режим Agent для автоматических многофайловых задач и доступ к передовым моделям (Claude, GPT, Gemini). Каждый платный план включает месячный пул кредитов на премиум-модели, равный стоимости плана.', ms: 'Cursor ialah editor kod AI (berasaskan VS Code) dengan pelengkapan tab sangat pantas, mod Agent yang menyelesaikan tugas pelbagai fail secara automatik, dan akses model frontier (Claude, GPT, Gemini). Setiap pelan berbayar termasuk kuota kredit penggunaan model premium senilai harga pelan.', hi: 'Cursor एक AI कोड एडिटर है (VS Code पर आधारित) — सुपर-फास्ट टैब पूर्णता, मल्टी-फ़ाइल कार्य स्वतः पूरा करने वाला Agent मोड, और फ्रंटियर मॉडल (Claude, GPT, Gemini) तक पहुंच। हर भुगतान प्लान में प्लान मूल्य के बराबर प्रीमियम-मॉडल उपयोग क्रेडिट शामिल।', de: 'Cursor ist ein KI-Code-Editor (auf VS-Code-Basis) mit blitzschneller Tab-Vervollständigung, einem Agent-Modus für automatische Mehrdatei-Aufgaben und Zugang zu Frontier-Modellen (Claude, GPT, Gemini). Jeder kostenpflichtige Plan enthält ein monatliches Guthaben für Premium-Modellnutzung in Höhe des Planpreises.', vi: 'Cursor là trình soạn mã AI (dựa trên VS Code) với tab completion siêu nhanh, chế độ Agent tự động hoàn thành tác vụ đa tệp, và truy cập các mô hình hàng đầu (Claude, GPT, Gemini). Mỗi gói trả phí gồm hạn mức tín dụng dùng mô hình cao cấp bằng giá gói.' },
    features: {
      en: ['Super-fast tab completion & unlimited Auto mode', 'Agent mode for automatic multi-file tasks', 'Access to frontier models (Claude, GPT, Gemini)', 'Premium-model usage credits per plan'],
      zh: ['超快 Tab 补全与无限 Auto 模式', '自动完成跨文件任务的 Agent 模式', '访问前沿模型（Claude、GPT、Gemini）', '按套餐分配高级模型用量额度'],
      ja: ['超高速タブ補完と無制限のAutoモード', '複数ファイルを自動処理するAgentモード', 'フロンティアモデル（Claude、GPT、Gemini）にアクセス', 'プランごとのプレミアムモデル利用クレジット'],
      ru: ['Сверхбыстрое tab-дополнение и безлимитный Auto-режим', 'Agent-режим для автоматических многофайловых задач', 'Доступ к моделям Claude, GPT, Gemini', 'Кредиты на премиум-модели по плану'],
      ms: ['Pelengkapan tab sangat pantas & mod Auto tanpa had', 'Mod Agent untuk tugas pelbagai fail automatik', 'Akses model frontier (Claude, GPT, Gemini)', 'Kredit penggunaan model premium ikut pelan'],
      hi: ['सुपर-फास्ट टैब पूर्णता और असीमित Auto मोड', 'मल्टी-फ़ाइल कार्य के लिए Agent मोड', 'फ्रंटियर मॉडल (Claude, GPT, Gemini) तक पहुंच', 'प्रति प्लान प्रीमियम-मॉडल उपयोग क्रेडिट'],
      de: ['Blitzschnelle Tab-Vervollständigung & unbegrenzter Auto-Modus', 'Agent-Modus für automatische Mehrdatei-Aufgaben', 'Zugang zu Frontier-Modellen (Claude, GPT, Gemini)', 'Premium-Modell-Guthaben je Plan'],
      vi: ['Tab completion siêu nhanh & Auto mode không giới hạn', 'Agent mode cho tác vụ đa tệp tự động', 'Truy cập mô hình hàng đầu (Claude, GPT, Gemini)', 'Tín dụng dùng mô hình cao cấp theo gói'],
    },
  },
  qoder: {
    tagline: { en: 'Agentic coding platform with Quest Mode & Repo Wiki.', zh: '具备 Quest 模式与 Repo Wiki 的智能体编程平台。', ja: 'Quest モードと Repo Wiki を備えたエージェント型コーディング基盤。', ru: 'Агентная платформа кодирования с Quest Mode и Repo Wiki.', ms: 'Platform pengekodan agentik dengan Quest Mode & Repo Wiki.', hi: 'Quest मोड और Repo Wiki के साथ एजेंटिक कोडिंग प्लेटफ़ॉर्म।', de: 'Agentische Coding-Plattform mit Quest Mode & Repo Wiki.', vi: 'Nền tảng lập trình agentic với Quest Mode & Repo Wiki.' },
    description: { en: "Qoder is Alibaba's agentic coding platform for real software development. It includes Quest Mode for autonomous task delegation, Repo Wiki that auto-generates documentation, unlimited completions & edits, and a credit system for chat and agent requests per plan.", zh: 'Qoder 是阿里巴巴面向真实软件开发的智能体编程平台。包含用于自主任务委派的 Quest 模式、自动生成文档的 Repo Wiki、无限补全与编辑，以及按套餐分配的聊天与 agent 请求额度。', ja: 'Qoder は実開発向けの Alibaba のエージェント型コーディング基盤。自律的なタスク委任の Quest モード、ドキュメントを自動生成する Repo Wiki、無制限の補完・編集、プランごとのチャット/agent リクエスト用クレジットを備えます。', ru: 'Qoder — агентная платформа кодирования от Alibaba для реальной разработки. Включает Quest Mode для автономного делегирования задач, Repo Wiki с авто-документацией, безлимитные дополнения и правки, а также систему кредитов на чат и запросы агента по плану.', ms: 'Qoder ialah platform pengekodan agentik Alibaba untuk pembangunan perisian sebenar. Termasuk Quest Mode untuk delegasi tugas autonomi, Repo Wiki yang menjana dokumentasi automatik, pelengkapan & suntingan tanpa had, dan sistem kredit untuk permintaan chat & agent ikut pelan.', hi: 'Qoder, असली सॉफ़्टवेयर विकास के लिए Alibaba का एजेंटिक कोडिंग प्लेटफ़ॉर्म है। इसमें स्वायत्त कार्य सौंपने हेतु Quest मोड, स्वतः दस्तावेज़ बनाने वाला Repo Wiki, असीमित पूर्णता व संपादन, और प्रति प्लान चैट व agent अनुरोध हेतु क्रेडिट सिस्टम शामिल।', de: 'Qoder ist Alibabas agentische Coding-Plattform für echte Softwareentwicklung. Mit Quest Mode für autonome Aufgabendelegation, Repo Wiki zur automatischen Dokumentation, unbegrenzten Vervollständigungen & Bearbeitungen und einem Kreditsystem für Chat- und Agent-Anfragen je Plan.', vi: 'Qoder là nền tảng lập trình agentic của Alibaba cho phát triển phần mềm thực tế. Gồm Quest Mode để giao tác vụ tự động, Repo Wiki tự tạo tài liệu, hoàn thành & chỉnh sửa không giới hạn, và hệ thống tín dụng cho chat và yêu cầu agent theo gói.' },
    features: {
      en: ['Quest Mode — autonomous task delegation', 'Repo Wiki — automatic documentation', 'Unlimited completions & edits', 'Chat & agent credits per plan'],
      zh: ['Quest 模式 — 自主任务委派', 'Repo Wiki — 自动文档', '无限补全与编辑', '按套餐分配聊天与 agent 额度'],
      ja: ['Quest モード — 自律的なタスク委任', 'Repo Wiki — 自動ドキュメント', '無制限の補完・編集', 'プランごとのチャット/agent クレジット'],
      ru: ['Quest Mode — автономное делегирование задач', 'Repo Wiki — авто-документация', 'Безлимитные дополнения и правки', 'Кредиты на чат и агента по плану'],
      ms: ['Quest Mode — delegasi tugas autonomi', 'Repo Wiki — dokumentasi automatik', 'Pelengkapan & suntingan tanpa had', 'Kredit chat & agent ikut pelan'],
      hi: ['Quest मोड — स्वायत्त कार्य सौंपना', 'Repo Wiki — स्वतः दस्तावेज़', 'असीमित पूर्णता व संपादन', 'प्रति प्लान चैट व agent क्रेडिट'],
      de: ['Quest Mode — autonome Aufgabendelegation', 'Repo Wiki — automatische Dokumentation', 'Unbegrenzte Vervollständigungen & Bearbeitungen', 'Chat- & Agent-Guthaben je Plan'],
      vi: ['Quest Mode — giao tác vụ tự động', 'Repo Wiki — tài liệu tự động', 'Hoàn thành & chỉnh sửa không giới hạn', 'Tín dụng chat & agent theo gói'],
    },
  },
}

// Produk dipecah per tier sehingga id-nya berakhiran varian (mis.
// "claude-pro-1-bulan"). Cari "family" konten berdasarkan awalan id.
const FAMILY_KEYS = Object.keys(PRODUCT_I18N)
export const familyOf = (id) => FAMILY_KEYS.find((k) => id === k || id.startsWith(k + '-'))

// Ambil teks produk terlokalisasi; fallback ke nilai asli (Indonesia) bila tak ada.
export function localizedProduct(product, lang) {
  if (lang === 'id' || !product) return product
  const tr = PRODUCT_I18N[familyOf(product.id)]
  if (!tr) return product
  return {
    ...product,
    tagline: tr.tagline?.[lang] || product.tagline,
    description: tr.description?.[lang] || product.description,
    features: tr.features?.[lang] || product.features,
  }
}

// Terjemahkan satuan periode kartu (mis. "bln", "12 bln", "paket").
export function localizePeriod(period, t) {
  if (!period) return period
  return period
    .replace(/\bbln\b/g, t('unit.mo'))
    .replace(/\bpaket\b/g, t('unit.pack'))
}

// Terjemahkan label tier (mis. "1 Bulan", "1.000 request") via token.
export function localizeTier(label, t) {
  if (!label) return label
  return label
    .replace(/\bBulan\b/g, t('tier.month'))
    .replace(/\bTahunan\b/g, t('tier.yearly'))
    .replace(/\bTahun\b/g, t('tier.year'))
    .replace(/\brequest\b/g, t('tier.requests'))
    .replace(/\bkredit\b/g, t('tier.credits'))
}

// Terjemahkan catatan tier (mis. "Hemat ~17%", "Populer").
export function localizeNote(note, t) {
  if (!note) return note
  const exact = {
    'Populer': t('tier.popular'),
    'Hemat': t('tier.save'),
    'Limit tertinggi': t('tier.highestLimit'),
    'Power user': t('tier.powerUser'),
    'Per bln, hemat 20%': t('tier.perMonthSave'),
  }
  if (exact[note]) return exact[note]
  return note
    .replace(/^Paling hemat/i, t('tier.mostSave'))
    .replace(/^Hemat/i, t('tier.save'))
    .replace(/\bkredit\b/g, t('tier.credits'))
}
