// Konten ulasan seed — SUMBER TUNGGAL yang dipakai bersama oleh
// prisma/seedReviews.js (seed awal) dan src/reviewShuffle.js (penambah harian).
// Persona diperluas agar penambahan 1-2 ulasan/hari bisa bertahan lama.

// ── Persona reviewer: [nama, bahasa, gender] ─────────────────────────────────
export const PERSONAS = [
  // Indonesia
  ['Budi Santoso', 'id', 'm'], ['Rizki Pratama', 'id', 'm'], ['Dewi Lestari', 'id', 'f'],
  ['Agus Setiawan', 'id', 'm'], ['Putri Maharani', 'id', 'f'], ['Andi Wijaya', 'id', 'm'],
  ['Siti Rahayu', 'id', 'f'], ['Bayu Saputra', 'id', 'm'], ['Nabila Az-zahra', 'id', 'f'],
  ['Fajar Ramadhan', 'id', 'm'], ['Indah Permata', 'id', 'f'], ['Doni Kurniawan', 'id', 'm'],
  ['Rina Wati', 'id', 'f'], ['Eko Prasetyo', 'id', 'm'], ['Maya Sari', 'id', 'f'], ['Hendra Gunawan', 'id', 'm'],
  ['Rahmat Hidayat', 'id', 'm'], ['Yusuf Maulana', 'id', 'm'], ['Arief Nugroho', 'id', 'm'],
  ['Fitri Handayani', 'id', 'f'], ['Sri Wahyuni', 'id', 'f'], ['Lina Marlina', 'id', 'f'],
  ['Aditya Firmansyah', 'id', 'm'], ['Rizky Ramadhan', 'id', 'm'], ['Taufik Hidayat', 'id', 'm'],
  ['Dian Puspita', 'id', 'f'], ['Ratna Sari', 'id', 'f'], ['Ahmad Fauzi', 'id', 'm'],
  ['Citra Ayu', 'id', 'f'], ['Dedi Setiawan', 'id', 'm'], ['Nurul Aini', 'id', 'f'],
  ['Galih Prakoso', 'id', 'm'], ['Intan Nuraini', 'id', 'f'], ['Wahyu Kurnia', 'id', 'm'],
  ['Sari Dewi', 'id', 'f'], ['Rudi Hartono', 'id', 'm'], ['Melati Putri', 'id', 'f'],
  ['Bambang Susilo', 'id', 'm'], ['Karina Salsabila', 'id', 'f'], ['Irfan Maulana', 'id', 'm'],
  ['Lestari Ningsih', 'id', 'f'], ['Yoga Pratama', 'id', 'm'], ['Anggi Saputri', 'id', 'f'],
  ['Dimas Anggara', 'id', 'm'], ['Ratih Kusuma', 'id', 'f'], ['Arif Rahman', 'id', 'm'],
  ['Zahra Amelia', 'id', 'f'], ['Fikri Ananda', 'id', 'm'], ['Salsa Bila', 'id', 'f'],
  ['Hasan Basri', 'id', 'm'], ['Nadia Rahma', 'id', 'f'], ['Reza Pratama', 'id', 'm'],
  // English
  ['Jake Miller', 'en', 'm'], ['Emily Carter', 'en', 'f'], ['Liam Walker', 'en', 'm'],
  ['Sophia Bennett', 'en', 'f'], ['Noah Reed', 'en', 'm'], ['Olivia Brooks', 'en', 'f'],
  ['Ethan Hayes', 'en', 'm'], ['Ava Morgan', 'en', 'f'], ['Mason Cooper', 'en', 'm'],
  ['Mia Foster', 'en', 'f'], ['Lucas Gray', 'en', 'm'], ['Chloe Turner', 'en', 'f'],
  ['Daniel Price', 'en', 'm'], ['Grace Sullivan', 'en', 'f'], ['Ryan Cole', 'en', 'm'], ['Hannah Ross', 'en', 'f'],
  ['Adam Wilson', 'en', 'm'], ['Jack Thompson', 'en', 'm'], ['Ben Carter', 'en', 'm'],
  ['Emma Watson', 'en', 'f'], ['Lily Evans', 'en', 'f'], ['Zoe Parker', 'en', 'f'],
  ['Owen Stewart', 'en', 'm'], ['Ella Brooks', 'en', 'f'], ['Felix Morgan', 'en', 'm'],
  ['Nora James', 'en', 'f'], ['Henry Ward', 'en', 'm'], ['Ivy Sanders', 'en', 'f'],
  ['Leo Hughes', 'en', 'm'], ['Ruby Foster', 'en', 'f'], ['Max Turner', 'en', 'm'],
  ['Alice Bennett', 'en', 'f'], ['Tom Harris', 'en', 'm'], ['Molly Carter', 'en', 'f'],
  ['Charlie Young', 'en', 'm'], ['Sophie Clarke', 'en', 'f'], ['George King', 'en', 'm'],
  // China
  ['王伟', 'zh', 'm'], ['李娜', 'zh', 'f'], ['张敏', 'zh', 'f'], ['刘洋', 'zh', 'm'],
  ['陈静', 'zh', 'f'], ['杨帆', 'zh', 'm'], ['黄磊', 'zh', 'm'], ['周婷', 'zh', 'f'],
  ['吴俊', 'zh', 'm'], ['徐丽', 'zh', 'f'], ['孙浩', 'zh', 'm'], ['朱琳', 'zh', 'f'],
  ['马涛', 'zh', 'm'], ['胡燕', 'zh', 'f'], ['郭鹏', 'zh', 'm'], ['林夏', 'zh', 'f'],
  ['赵强', 'zh', 'm'], ['王磊', 'zh', 'm'], ['刘军', 'zh', 'm'], ['孙丽', 'zh', 'f'], ['赵敏', 'zh', 'f'],
  ['钱伟', 'zh', 'm'], ['周芳', 'zh', 'f'], ['吴涛', 'zh', 'm'], ['郑欣', 'zh', 'f'],
  ['冯军', 'zh', 'm'], ['蒋琳', 'zh', 'f'], ['沈浩', 'zh', 'm'], ['韩雪', 'zh', 'f'],
  ['杨晨', 'zh', 'm'], ['朱婷', 'zh', 'f'], ['秦亮', 'zh', 'm'], ['许静', 'zh', 'f'],
  ['何军', 'zh', 'm'], ['吕慧', 'zh', 'f'], ['施洋', 'zh', 'm'], ['张倩', 'zh', 'f'],
  ['曹磊', 'zh', 'm'], ['严丽', 'zh', 'f'], ['华强', 'zh', 'm'], ['金燕', 'zh', 'f'],
  // Vietnam
  ['Nguyễn Văn An', 'vi', 'm'], ['Trần Thị Hương', 'vi', 'f'], ['Lê Minh Tuấn', 'vi', 'm'],
  ['Phạm Thu Hà', 'vi', 'f'], ['Hoàng Văn Nam', 'vi', 'm'], ['Vũ Thị Lan', 'vi', 'f'],
  ['Đặng Quốc Bảo', 'vi', 'm'], ['Bùi Thị Mai', 'vi', 'f'], ['Đỗ Văn Hùng', 'vi', 'm'],
  ['Ngô Thị Thảo', 'vi', 'f'], ['Dương Minh Khoa', 'vi', 'm'], ['Lý Thị Ngọc', 'vi', 'f'],
  ['Phan Văn Đức', 'vi', 'm'], ['Võ Thị Linh', 'vi', 'f'], ['Đinh Quang Huy', 'vi', 'm'], ['Trịnh Thu Trang', 'vi', 'f'],
  ['Trần Văn Long', 'vi', 'm'], ['Lê Quang Minh', 'vi', 'm'], ['Nguyễn Thị Hồng', 'vi', 'f'], ['Phạm Thị Lan', 'vi', 'f'],
  ['Vương Quốc Anh', 'vi', 'm'], ['Lê Thị Hoa', 'vi', 'f'], ['Phạm Đức Duy', 'vi', 'm'],
  ['Trần Thu Hà', 'vi', 'f'], ['Nguyễn Văn Dũng', 'vi', 'm'], ['Bùi Thị Hạnh', 'vi', 'f'],
  ['Hoàng Minh Tuấn', 'vi', 'm'], ['Đào Thị Thắm', 'vi', 'f'], ['Lê Đức Anh', 'vi', 'm'],
  ['Vũ Ngọc Ánh', 'vi', 'f'], ['Nguyễn Đức Huy', 'vi', 'm'], ['Phan Thu Trang', 'vi', 'f'],
  ['Trương Quốc Huy', 'vi', 'm'], ['Hà Thị Thu', 'vi', 'f'], ['Đỗ Minh Long', 'vi', 'm'],
  ['Ngô Thu Hằng', 'vi', 'f'], ['Lâm Đức Phát', 'vi', 'm'], ['Tô Thị Hồng', 'vi', 'f'],
  // Japan
  ['田中翔太', 'ja', 'm'], ['佐藤美咲', 'ja', 'f'], ['鈴木大輔', 'ja', 'm'], ['高橋愛', 'ja', 'f'],
  ['伊藤健一', 'ja', 'm'], ['渡辺さくら', 'ja', 'f'], ['山本拓也', 'ja', 'm'], ['中村優子', 'ja', 'f'],
  ['小林直樹', 'ja', 'm'], ['加藤陽菜', 'ja', 'f'], ['吉田亮', 'ja', 'm'], ['山田真央', 'ja', 'f'],
  ['佐々木涼', 'ja', 'm'], ['松本ゆい', 'ja', 'f'], ['井上和也', 'ja', 'm'], ['木村彩', 'ja', 'f'],
  ['高橋直人', 'ja', 'm'], ['松本健', 'ja', 'm'], ['藤原千夏', 'ja', 'f'], ['山口美月', 'ja', 'f'],
  ['森田大輝', 'ja', 'm'], ['岡田結衣', 'ja', 'f'], ['石井亮', 'ja', 'm'], ['上野舞', 'ja', 'f'],
  ['前田直樹', 'ja', 'm'], ['石川さくら', 'ja', 'f'], ['長谷川翔', 'ja', 'm'], ['藤井美月', 'ja', 'f'],
  ['村上大輔', 'ja', 'm'], ['清水玲奈', 'ja', 'f'], ['青木悠', 'ja', 'm'], ['林あかり', 'ja', 'f'],
  ['金子健太', 'ja', 'm'], ['小川美咲', 'ja', 'f'], ['斎藤大和', 'ja', 'm'], ['近藤葵', 'ja', 'f'],
  ['三浦翔平', 'ja', 'm'], ['大野美優', 'ja', 'f'], ['工藤亮太', 'ja', 'm'], ['杉山結菜', 'ja', 'f'],
]

// ── Komentar gaya manusia biasa (santai, ada sedikit kritik, overall positif) ──
export const COMMENTS = {
  id: [
    'mantap sih ini, prosesnya cepet bgt ga sampe 10 menit udah masuk',
    'awalnya ragu takut kena tipu, ternyata legit. makasih bang',
    'udah langganan 3 bulan aman2 aja, lanjut terus dah',
    'harga miring kualitas oke, recommended pokoknya',
    'fast respon, adminnya ramah juga. bintang 5 deh',
    'akun normal ga ada masalah, login lancar jaya',
    'telat dikit tadi tp akhirnya masuk juga, overall puas',
    'murah meriah, dibanding beli langsung jauh lebih hemat',
    'garansinya kepake kemaren akun bermasalah langsung diganti, top',
    'ga nyangka semurah ini bisa dapet akun ori, gokil',
    'pelayanan cepat barang sesuai deskripsi, thanks gan',
    'transaksi ke sekian kali tetep aman, langganan disini terus',
    'respon agak lama tp hasilnya memuaskan kok',
    'baru pertama beli disini dan ga kecewa, bakal balik lagi',
    'akun aktif sesuai durasi, ga ada drama. mantul',
    'cuss langsung aktif ga ribet, recommended seller',
    'worth it bgt harganya, premium beneran bukan abal2',
    'sempet error pas login tp dibantu sampe beres, makasih adminnya',
    'lebih murah dari official fungsi sama persis, puas',
    'pengiriman kilat ga sampe 5 menit udh dpt akunnya',
    'udah 2x order disini lancar terus, trusted lah',
    'akunnya private bukan sharing, aman dipake kerja',
    'ngebantu bgt buat kerjaan, harganya bersahabat',
    'oke punya sesuai ekspektasi, lanjutkan bos',
    'csnya responsif bgt, pertanyaan dijawab cepet',
    'prosesnya cepet sih, cuma pas malam chat admin kadang lama dibales. overall aman',
    'akunnya oke, minusnya tadi sempet nunggu bentar pas jam sibuk',
    'biasanya cepet, kemaren sempet delay dikit tapi masih bisa ditolerir lah',
    'harga naik dikit dari kemaren tapi masih worth it banget',
    'dapet akun sesuai pesenan, cuma perlu sabar dikit nunggu prosesnya',
    'lumayan sih, harapannya jangan sampe telat lagi kayak kemaren',
    'barangnya bagus, cuma cara penyerahan akunnya agak ribet buat pemula',
    'okelah ini, admin fast respon walau sempet antri dikit',
    'seneng sih dapet harga gini, semoga stoknya ga cepet habis terus',
    '2x beli disini, pernah sekali telat dikit tapi diganti garansi, fair lah',
    'keren sih, cuma semoga next time estimasi waktunya lebih akurat',
    'produk ori gass, sebentar lagi nyobain yang 1 tahun',
    'beneran worth it, walau sempet ragu pas pertama kali karena harganya kemurahan. haha',
    'aman terkendali, sempet down sekali tapi cepat dibantu',
    'mantap lah, semoga makin banyak pilihan produknya',
  ],
  en: [
    'works perfectly, got my account in like 5 mins. legit seller',
    'was a bit skeptical at first but its 100% legit, thanks!',
    'been using it for 2 months now, no issues at all',
    'way cheaper than official and works the same, no complaints',
    'fast delivery and friendly support, easy 5 stars',
    'account works fine, login was smooth no problems',
    'took a little while but worth the wait, happy customer',
    'honestly didnt expect it to be this smooth, recommended',
    'great price for premium quality, will buy again',
    'had a small issue and support fixed it right away, top notch',
    'super fast, the account was ready almost instantly',
    'ordered a few times now and its always reliable',
    'support was a bit slow to reply but sorted it out in the end',
    'first time buying here and not disappointed at all',
    'private account not shared, safe to use for work',
    'cant believe how cheap this is for an original account',
    'smooth transaction, item exactly as described. cheers',
    'saved me a lot of money compared to paying full price',
    'legit, fast and cheap, what more can you ask for',
    'account stayed active the whole duration, no drama',
    'delivery was basically instant, didnt even have to wait',
    'really helpful for my work and great value too',
    'everything as promised, solid seller 👍',
    'no issues so far, already a month in',
    'quick reply and super easy process, thanks a lot',
    'smooth overall, just wish the reply was a bit faster at night',
    'account works great, but the wait was longer than expected once',
    'good value, though the process could be a bit simpler for beginners',
    'solid seller, had one small delay but they sorted it out quickly',
    'everything fine, just the price went up a little since last time',
    'great deal, hope they keep stock so it doesnt run out',
    'happy with it, but please improve the estimated delivery time',
    'second purchase here, once was a bit late but the warranty covered it',
    'feels almost too cheap to be true, but its legit haha',
    'no complaints really, just wish there were more product options',
  ],
  zh: [
    '很快就到账了，五分钟不到，靠谱',
    '一开始有点担心怕被骗，结果是真的，谢谢老板',
    '已经用了两个月了一点问题都没有',
    '比官方便宜太多了功能一样，满意',
    '发货快客服态度也好，五星好评',
    '账号正常登录很顺畅，没毛病',
    '等了一小会儿不过值了，挺满意的',
    '没想到这么顺利，推荐给大家',
    '价格实惠质量也不错，下次还来',
    '之前有点小问题客服马上就解决了，赞一个',
    '基本秒到账，几乎不用等',
    '买过好几次了一直都很稳',
    '客服回复稍微慢了点不过最后还是解决了',
    '第一次买没有失望，会回购的',
    '是独享号不是共享的，工作用很安全',
    '这个价格能买到正版真是没想到',
    '交易很顺利和描述一样，谢谢',
    '比原价省了不少钱',
    '又便宜又快又靠谱，没得挑',
    '账号整个周期都正常，没有幺蛾子',
    '物超所值，强烈推荐',
    '客服很耐心，问什么都很快回',
    '整体挺好的，就是晚上客服回复有点慢',
    '账号没问题，就是有一次等得比预计久了一点',
    '性价比不错，就是流程对新人不算特别友好',
    '靠谱的卖家，有一次小延迟但处理得挺好',
    '东西不错，就是价格比之前涨了一点',
    '很划算，希望别总是断货',
    '挺满意的，就是希望预估时间能更准一些',
    '第二次买了，有一次稍晚但保修都搞定了',
    '价格便宜得有点不敢相信，但确实是真的哈哈',
    '没什么好挑的，希望商品种类再多一点',
  ],
  vi: [
    'nhanh thật chưa tới 5 phút đã có tài khoản, uy tín',
    'lúc đầu hơi lo bị lừa nhưng đúng là thật, cảm ơn shop',
    'dùng 2 tháng rồi mà không lỗi gì cả',
    'rẻ hơn official nhiều mà xài y chang, ưng',
    'giao nhanh hỗ trợ nhiệt tình, 5 sao',
    'tài khoản đăng nhập mượt không vấn đề gì',
    'chờ chút xíu nhưng đáng, hài lòng nha',
    'không ngờ mượt vậy luôn, recommend',
    'giá ổn chất lượng tốt, lần sau ghé tiếp',
    'bị lỗi nhẹ shop fix liền, quá ok',
    'vào tài khoản gần như tức thì',
    'mua mấy lần rồi lần nào cũng ổn',
    'shop rep hơi chậm tí nhưng cuối cùng cũng xong',
    'lần đầu mua mà không thất vọng, sẽ quay lại',
    'tài khoản riêng không phải dùng chung, yên tâm làm việc',
    'giá này mà có acc xịn thì hết nước chấm',
    'giao dịch suôn sẻ đúng như mô tả, cảm ơn',
    'tiết kiệm được khối tiền so với mua thẳng',
    'rẻ nhanh uy tín, còn gì bằng',
    'tài khoản dùng đủ hạn không drama gì hết',
    'đáng đồng tiền, sẽ giới thiệu bạn bè',
    'cskh tư vấn nhiệt tình trả lời nhanh',
    'ổn chung chung, tối shop rep hơi chậm xíu',
    'tài khoản xài ngon, có lần chờ lâu hơn dự kiến chút',
    'giá ổn, tiếc là quy trình hơi khó cho người mới',
    'shop uy tín, có lần giao hơi trễ nhưng xử lý tốt',
    'hàng ok, mà giá có tăng nhẹ so với lần trước',
    'đáng mua, mong đừng hết hàng hoài',
    'hài lòng, mong thời gian dự kiến chuẩn hơn',
    'mua lần 2 rồi, có lần hơi trễ nhưng được bảo hành',
    'rẻ tới mức hơi nghi, nhưng thật 100% haha',
    'không có gì chê, mong shop thêm nhiều sản phẩm',
  ],
  ja: [
    '5分くらいで届きました、ちゃんとしてます',
    '最初は不安でしたが本物でした、ありがとうございます',
    '2ヶ月使ってますが全く問題ないです',
    '公式よりかなり安いのに同じように使えて満足',
    '発送早いしサポートも丁寧、星5つ',
    'アカウント普通にログインできて問題なしでした',
    '少し待ちましたが待つ価値ありでした',
    'こんなにスムーズだと思わなかった、おすすめ',
    '安いのに品質もいい、また買います',
    'ちょっとトラブったけどすぐ対応してくれた、最高',
    'ほぼ即時に届きました',
    '何回か買ってるけど毎回安定してます',
    '返信は少し遅めでしたが最終的に解決しました',
    '初めて買いましたが全然問題なかったです',
    '共有じゃなく専用アカウントなので仕事でも安心',
    'この値段で正規が手に入るとは思わなかった',
    '取引スムーズで説明通りでした、感謝',
    '正規で買うよりかなり節約できました',
    '安い早い安心、文句なしです',
    '期間中ずっと使えてトラブルなしでした',
    'コスパ最高、リピートします',
    'サポートの対応が早くて助かりました',
    '全体的に良いですが、夜は返信が少し遅めでした',
    'アカウントは問題なし、一度だけ予想より待ちました',
    'コスパはいいけど、初心者には少し手順が分かりにくいかも',
    '信頼できるショップ、一度小さい遅れがあったけど対応は良かった',
    '商品は良いけど前回より少し値段上がってた',
    'お買い得、在庫切れにならないといいな',
    '満足してます、予想時間がもう少し正確だと嬉しい',
    '2回目の購入、一度遅れたけど保証で対応してくれた',
    '安すぎて逆に心配だったけど、ちゃんと本物でした笑',
    '文句なし、商品ラインナップがもっと増えるといいな',
  ],
}

const rnd = (n) => Math.floor(Math.random() * n)
export const pick = (arr) => arr[rnd(arr.length)]
export const weightedRating = () => { const r = Math.random(); return r < 0.62 ? 5 : r < 0.9 ? 4 : 3 }

// Bangun daftar persona LENGKAP: email & avatar konsisten untuk semua pemakai
// (seed & penambah harian). Foto randomuser.me per gender cuma ada index 0-99,
// jadi nomor potret di-modulo 100 agar selalu valid meski persona > 100.
export function buildPersonas() {
  const genderCount = { m: 0, f: 0 }
  return PERSONAS.map(([name, lang, gender], i) => {
    genderCount[gender] += 1
    const num = (genderCount[gender] - 1) % 100
    return {
      email: `reviewer-${i}@reviews.local`,
      name,
      lang,
      gender,
      avatar: `https://randomuser.me/api/portraits/${gender === 'f' ? 'women' : 'men'}/${num}.jpg`,
    }
  })
}
